### ISSUE TITLE
Init Problem with the blinds

### ISSUE THREAD

**Issue by RkcCorian** [holomekc/ioBroker.bshb#90] opened 2021-12-11 22:33 UTC
**Describe the bug**  
When I restart ioBroker, very often the blind level and the window / door opening sensor is initialized wrong.

**To Reproduce**  
Restart ioBroker and check the blind levels and the window / door open info

**Expected behavior**  
Correct Level + window / door open info after ioBroker startup

**Screenshots & Logfiles**  
If applicable, add screenshots and logfiles to help explain your problem.

**Versions:**
- Adapter version: 0.1.16
- JS-Controller version: 3.3.21
- Node version: v14.18.1
- Operating system: synology docker

**Additional context**

**Comment by holomekc** [comment] 2021-12-22 10:35
Thank you for the feedback. I will take a look as soon as I find some time.

**Comment by holomekc** [comment] 2021-12-24 23:49
I thing the issue is that the callback of setObjectNotExists is not called when the object already exists. I need to take a closer look if/how I can overcome this, so that I set the value still after creation when the object does not exist yet but also set it when it already exists.

See: src/controller/handler/bshb-open-door-window-handler.ts

**Comment by holomekc** [comment] 2022-01-06 11:27
0.1.17 is available on GitHub master branch. For me it looks good. I will test for a while before updating via ioBroker. You can install the new version directly via GitHub to test as well. Feedback would be awesome.

**Comment by RkcCorian** [comment] 2022-01-06 17:50
Many thanks! I will try :-)

**Comment by RkcCorian** [comment] 2022-01-18 11:11
I restarted my ioBroker during night. Now I realized the problem still exists unfortunately.

**Comment by holomekc** [comment] 2022-01-18 12:27
Hmm. When I stop the bshb instance. Then change the temperature via Bosch App. Then start the bshb instance I directly see the updated temperature. I also tested with privacy mode of camera and the window / door opening. So for the last one. I stopped bshb instance, opened my window, start bshb instance and I can see that the values changes accordingly.

I have no blinds sadly so I cannot test that, but to be honest that does not make much of a difference. The devices / services provided by the controller are all handled the same way.

To have a closer look why this does not work for you I guess I need some logs to check what is happening. You can configure silly log level and during startup of the bshb instance and then check logs:
For blinds:
```
content: - ["[{\"@type\":\"DeviceServiceData\"...
```
For window / door (search for Detecting open doors/windows finished and then above check the content
```
response information:
status: - [200]
Detecting open doors/windows finished
content: - 
```
```json
[
   {
      "allDoors":[],
      "openDoors":[],
      "unknownDoors":[],
      "allWindows":[],
      "openWindows":[],
      "unknownWindows":[],
      "allOthers":[],
      "openOthers":[],
      "unknownOthers":[]
   }
]
```

When you then search in the browser for the iobroker object id (e.g. setpointTemperature) you should see what value the adapter received from the controller. When this does not match the expectation than there is not much what I can do. If you say the value in this response is correct, but I do not see the value in iobroker then something is wrong with the adapter. But I am still wondering why this works for me.

Example:
bshb.instance stopped when window is open
![image](https://user-images.githubusercontent.com/30546982/149935485-ec16c89c-ac95-4348-87c9-61992d3232df.png)

Close window. Value does not change in iobroker obviously ;)

Start bshb instance and check again in objects:
![image](https://user-images.githubusercontent.com/30546982/149937106-f0c78454-bfea-4384-8e38-6b30cb440251.png)

and logs:
```json
[
  {
    "allDoors":[
      {
        "name":"Eingangstür",
        "roomName":"Flur"
      }
    ],
    "openDoors":[],
    "unknownDoors":[],
    "allWindows":[
      {
        "name":"Fensterkontakt",
        "roomName":"Schlafzimmer"
      },
      {
        "name":"Fenster",
        "roomName":"Wohnzimmer"
      }
    ],
    "openWindows":[],
    "unknownWindows":[],
    "allOthers":[],
    "openOthers":[],
    "unknownOthers":[]
  }
]
```


I hope this helps to find out what is not working properly.

**Comment by RkcCorian** [comment] 2022-01-18 14:08
Many thanks / Vielen Dank! I will try at the weekend when I can invest some time in this.

**Comment by RkcCorian** [comment] 2022-01-22 17:36
I checked again more in details and I'm totally confused...
What I did...
- Open Blind and Close Window
- Stop Container
- Close Blind
- Start Container
- Check values

What I see...
- The data in the adapter is OK (Blind + OpenWindowSensor)
- At the ALIAS also the value is correct (Blind is in closed state + Window is closed)
- BUT JARVIS and the BlocklyScript still have the old value (Blind open)
- When I overwrite the closed value (Level=0) with the EXCACT same value (0) JARVIS and BlocklyRealize is detect the Blind also as closed

This is strange for me!

Adapter + ALIAS value is OK but JARVIS + Blockly-Script using the ALIAS are wrong. If I remember correctly I checked also once without ALIAS by using the Adapter value directly but this was the same behaviour.

Any idea????

**Comment by holomekc** [comment] 2022-01-22 19:21
Hmm I don't think that I am setting the values differently at startup. But I will check. But this helps already. I will try to reproduce your described issue and check if we can do something about that.

**Comment by RkcCorian** [comment] 2022-01-22 19:26
One hint... I was only able to reproduce the error when restarting the docker container. By starting & stopping the adapter the error was not reproducable by me

**Comment by holomekc** [comment] 2022-01-22 19:37
Hmm ok. I will take a look. But than it sounds like bshb. Adapter starts adjust values before even the scripts adapter starts. How are you register to the values? This sound to me like that the script is just liste. To changes and on startup it does not check the latest value.

you could test this actually as well. Do the same as you already did but also stop scripts and start it after you started bshb.

**Comment by RkcCorian** [comment] 2022-01-22 19:44
I will try later.... **BUT** JARVIS also has the same wrong value then my Blockly Script and that is totally independent. The Script executes on standard triggers.

**Comment by RkcCorian** [comment] 2022-01-22 21:37
Restarting JARVIS and Javascript adapter does not help

I did the following test...

I copy with a script the DP value from the  bshb adapter into another DP. But it is still the old value...
DP from adapter (in this buggy situation)
<img width="1783" alt="image" src="https://user-images.githubusercontent.com/79741077/150656196-4c63044a-e066-447d-b892-779eb75c4734.png">
Blockly for copy operation
<img width="592" alt="image" src="https://user-images.githubusercontent.com/79741077/150656208-b2fa4eee-6325-4e15-ac98-0dd73dc509a3.png">
Resulting DP show the value before the Container restart and before writting the value new
<img width="1706" alt="image" src="https://user-images.githubusercontent.com/79741077/150656232-ef42b72e-d379-44e4-9ecb-d94881d3e5e0.png">

**Comment by RkcCorian** [comment] 2022-01-22 21:47
I found now a workaround... I had the bshb adapter in the startup as "2 Datenprovider-Adapter" which makes the most sense to me. But this lead to my problem. Now I changed to "3 Andere Adapter" and I do not have this problem.
<img width="306" alt="image" src="https://user-images.githubusercontent.com/79741077/150656463-80a251d7-400a-4058-8bd9-a9fcaea81688.png">

To be honest... I do not have any glue how my above mentioned problems could happen. Typically when I copy data from a DP that I see it works under all conditions. I never had before that I copy from a DP and I get the old data. I'm not sure if this is even a problem of ioBroker (startup) itself.

**Comment by holomekc** [comment] 2022-01-22 21:51
Awesome. I checked the code again and still cannot find any other way of writing the state values. 

I am not surr how blocky works. I just now from javascript register to changes is not the same as reading the current value during startup.

when I have some time and I am in the mood 🤪 I can check blocky again. But i am happy that the startup order works for you

**Comment by holomekc** [comment] 2022-03-26 15:55
Hi. I close the issue. As mentioned there is nothing I can do on adapter side. If still could not check blockly... If you face further issues let me know.

**Closed by holomekc** 2022-03-26 15:55 UTC

**Comment by RkcCorian** [comment] 2022-03-26 17:35
Hi, ok für me. Many thanks for checking!! 😀
