### ISSUE TITLE
Need to pair after each Restart of the ioBroker

### ISSUE THREAD

**Issue by gigiCom** [holomekc/ioBroker.bshb#132] opened 2022-03-11 23:40 UTC
Hello,

after a restart of the ioBroker controller, I always need to pair again with my Bosch SHC, which is very uncomfortable. How can I avoid to always need to do a repairing after an ioBroker controller restart?

Btw. this does not happen with the Philips Hue connection 😄 .

Ciao!

**Comment by holomekc** [comment] 2022-03-26 15:53
Hi. This normally do not happen. Can you check your certificates stored in ioBroker. The adapter stores two values:

1. bshb_<identifier>_cert
2. bshb_<identifier>_key

It could also help to set logging to debug or even silly, so that you can see what the issue is.

**Comment by gigiCom** [comment] 2022-03-27 13:32
Hello,

can you briefly say where I can find these 2 values?

Under _Basic Settings > Certificates_, I find a bunch of certificates, all belonging to the SHC, at the top there are 2 default ones.

I also have the log here, but it does not help further:

<html>
<body>


2022-03-27 15:21:54.721 - info: bshb.0 (20440) Check if client with identifier: ioBroker.bshb_834a8f5e-a6d4-4f84-9c6e-e4f177a94f29 is already paired.
--
2022-03-27 15:21:55.181 - info: bshb.0 (20440) Client with identifier: ioBroker.bshb_834a8f5e-a6d4-4f84-9c6e-e4f177a94f29 was not paired yet.
2022-03-27 15:21:55.181 - info: bshb.0 (20440) Start pairing. Activate pairing on Bosch Smart Home Controller by pressing button until flashing.
2022-03-27 15:21:55.404 - warn: bshb.0 (20440) Could not pair client. Did you press the paring button on Bosch Smart Home Controller? Error details: Error: write EPROTO 16536:error:14094412:SSL routines:ssl3_read_bytes:sslv3 alert bad certificate:c:\ws\deps\openssl\openssl\ssl\record\rec_layer_s3.c:1544:SSL alert number 42
2022-03-27 15:22:05.416 - info: bshb.0 (20440) Check if client with identifier: ioBroker.bshb_834a8f5e-a6d4-4f84-9c6e-e4f177a94f29 is already paired.
2022-03-27 15:22:05.834 - info: bshb.0 (20440) Client with identifier: ioBroker.bshb_834a8f5e-a6d4-4f84-9c6e-e4f177a94f29 was not paired yet.
2022-03-27 15:22:05.835 - info: bshb.0 (20440) Start pairing. Activate pairing on Bosch Smart Home Controller by pressing button until flashing.
2022-03-27 15:22:06.050 - warn: bshb.0 (20440) Could not pair client. Did you press the paring button on Bosch Smart Home Controller? Error details: Error: write EPROTO 16536:error:14094412:SSL routines:ssl3_read_bytes:sslv3 alert bad certificate:c:\ws\deps\openssl\openssl\ssl\record\rec_layer_s3.c:1544:SSL alert number 42


</body>
</html>

The thing is still that I can not reconnect automatically to the SHC after a broker restart.

![image](https://user-images.githubusercontent.com/10831737/160283936-85edee02-c693-4e47-b60c-a6fba07df199.png)

![image](https://user-images.githubusercontent.com/10831737/160283946-364f2feb-a82d-4a88-a6b2-f7b9aedb05e7.png)

**Comment by holomekc** [comment] 2022-03-27 14:33
Hmm it looks like the adapter recreates certificates because identifier changes? Not 100% sure, but ids differ in the certificate configuration and in your log. This is actually strange, because normally this should not happen. I would recommend:
- stop adapter
- remove all certificates starting with bshb...
- go into adapter configuration and set an identifier by copying a value from here: https://www.uuidgenerator.net/
- save and start adapter and pair again.

I hope this helps. If not I need to take a closer look.

**Comment by gigiCom** [comment] 2022-03-27 15:55
Hi, yes, this helped. I did what you said and now the reconnect works.

The thing was most probably, that I haven't had any client ID defined in the SHC adapter settings at all.

Thanks for the help and ciao!

**Comment by holomekc** [comment] 2022-03-27 18:25
Ok awesome. I will check why the client ID is not set for a new setup. Thanks for the feedback. I will close the issue.

**Closed by holomekc** 2022-03-27 18:25 UTC
